table election
	lineageTag: b376700d-319b-4a74-bac6-8eabed6c5604

	column election_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 733f2b3f-86a9-434f-94b6-1d0069934d6a
		summarizeBy: none
		sourceColumn: election_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column annee_election
		dataType: int64
		formatString: 0
		lineageTag: 4a37f551-6db9-44bb-a7bf-9a84fc37793a
		summarizeBy: none
		sourceColumn: annee_election

		annotation SummarizationSetBy = User

	column tour
		dataType: int64
		formatString: 0
		lineageTag: 61a53194-07f3-4a60-9de2-9625595dfaf5
		summarizeBy: none
		sourceColumn: tour

		annotation SummarizationSetBy = User

	partition election = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-1-eu-west-3.pooler.supabase.com", "postgres"),
				    public_dim_election = Source{[Schema="public",Item="dim_election"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(public_dim_election,{{"election_sk", Int64.Type}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"election_nk"}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Colonnes supprimées",{{"tour", Int64.Type}, {"annee_election", Int64.Type}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

