table insee_electoral_data
	lineageTag: 8fbb2680-6e1f-4fe4-aa12-f6f3e4182626

	column annee
		dataType: int64
		formatString: 0
		lineageTag: f1ef171d-ff78-4c7c-837f-400ea69164b7
		summarizeBy: none
		sourceColumn: annee

		annotation SummarizationSetBy = User

	column electeurs_inscrits_sur_liste_principale
		dataType: double
		lineageTag: f0d542cc-4f18-43a8-9ccd-5f0db6974156
		summarizeBy: sum
		sourceColumn: electeurs_inscrits_sur_liste_principale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a4ce29a3-9ada-4370-a196-fc22b6625554
		summarizeBy: none
		sourceColumn: geo_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition insee_electoral_data = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-1-eu-west-3.pooler.supabase.com", "postgres"),
				    public_fact_insee_electoral_data = Source{[Schema="public",Item="fact_insee_electoral_data"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(public_fact_insee_electoral_data,{"fact_electoral_data_id"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

