table 'public fact_insee_historical_demography'
	lineageTag: 5269b5ce-0b29-48e6-afba-b8ef65ff089b

	column annee
		dataType: int64
		formatString: 0
		lineageTag: 99fca1ba-941a-401f-bc50-d9859837e3ec
		summarizeBy: none
		sourceColumn: annee

		annotation SummarizationSetBy = User

	column logements_dnbt
		dataType: double
		lineageTag: ed324f3e-6a58-46a9-9e68-1da5f4ebaf55
		summarizeBy: sum
		sourceColumn: logements_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column logements_vacants_dnbt
		dataType: double
		lineageTag: 30685093-e06c-4bcb-a4b0-ece36abd6530
		summarizeBy: sum
		sourceColumn: logements_vacants_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pop_menages_pop_res_princ_dnbt
		dataType: double
		lineageTag: 1dbfba54-194a-4937-b6d9-5086bf37425d
		summarizeBy: sum
		sourceColumn: pop_menages_pop_res_princ_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column population_dnbt
		dataType: double
		lineageTag: 049595be-cefc-4e6a-beba-9a58b3263737
		summarizeBy: sum
		sourceColumn: population_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column residences_principales_menages_dnbt
		dataType: double
		lineageTag: f0f92d19-f56f-49e4-b6d1-85d96c4a5d69
		summarizeBy: sum
		sourceColumn: residences_principales_menages_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column res_secondaires_et_logts_occasionnels_dnbt
		dataType: double
		lineageTag: aeaecc29-d48b-43d6-b285-e55674893284
		summarizeBy: sum
		sourceColumn: res_secondaires_et_logts_occasionnels_dnbt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0674b6cd-f49e-49a0-af98-9269b191ef9c
		summarizeBy: none
		sourceColumn: geo_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'public fact_insee_historical_demography' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-1-eu-west-3.pooler.supabase.com", "postgres"),
				    public_fact_insee_historical_demography = Source{[Schema="public",Item="fact_insee_historical_demography"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(public_fact_insee_historical_demography,{"fact_historical_demography_id"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

