table 'public fact_resultats_liste'
	lineageTag: 2b6f5207-373d-498c-8d60-14fe2d3aed9a

	column election_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 98f5b5c1-6c5e-4751-b8fd-c5051656889e
		summarizeBy: none
		sourceColumn: election_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column geo_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 25c05ce1-eb8c-46cf-80fc-820b0ee03c7b
		summarizeBy: none
		sourceColumn: geo_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column candidat_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4b090bd-ad62-48c1-a011-2e6bf78fef58
		summarizeBy: none
		sourceColumn: candidat_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column voix
		dataType: int64
		formatString: 0
		lineageTag: c8ccdc06-b1a0-4e97-bd96-9cab5afc8f55
		summarizeBy: sum
		sourceColumn: voix

		annotation SummarizationSetBy = Automatic

	partition 'public fact_resultats_liste' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("aws-1-eu-west-3.pooler.supabase.com", "postgres"),
				    public_fact_resultats_liste = Source{[Schema="public",Item="fact_resultats_liste"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(public_fact_resultats_liste,{"resultat_liste_id"}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes supprimées",{{"election_sk", Int64.Type}, {"geo_sk", Int64.Type}, {"candidat_sk", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

